food_plan/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from planner import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('auth/', views.auth_view, name='auth'),
    path('registration/', views.register_view, name='registration'),
    path('lk/', views.lk_view, name='lk'),
    path('order/', views.order_view, name='order'),
    path('card/', views.card, name='card'),
    path('logout/', views.logout_view, name='logout'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('card/<int:dish_id>/', views.dish_card, name='card'),
    path('update_avatar/', views.update_avatar, name='update_avatar'),
    path('create-payment/', views.create_payment, name='create_payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('yookassa-webhook/', views.yookassa_webhook, name='yookassa_webhook'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

planner/models.py
from django.db import models
from django.contrib.auth.models import User


class Allergy(models.Model):
    name = models.CharField(max_length=150, verbose_name='Аллергия')

    def __str__(self):
        return self.name


class DietType(models.Model):
    name = models.CharField(max_length=150, verbose_name='Тип диеты')

    def __str__(self):
        return self.name


class SubscriptionOrder(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Сумма заказа'
    )
    description = models.CharField(
        max_length=255,
        verbose_name='Описание подписки'
    )
    status = models.CharField(
        max_length=20,
        choices=[
            ('pending', 'Ожидает оплаты'),
            ('paid', 'Оплачен'),
            ('failed', 'Не удался')
        ],
        default='pending',
        verbose_name='Статус'
    )
    payment_id = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name='ID платежа'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )
    subscription_params = models.JSONField(
        default=dict,
        verbose_name='Параметры подписки'
    )
    payment_data = models.JSONField(
        null=True,
        blank=True,
        verbose_name='Данные платежа'
    )

    @property
    def is_active(self):
        return self.status == 'paid' and (
            self.user.userprofile.subscription_end_date >= timezone.now().date()
            if hasattr(self.user, 'userprofile') and self.user.userprofile.subscription_end_date
            else False
        )

    def __str__(self):
        return f"Заказ #{self.id} - {self.get_status_display()}"


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )
    allergies = models.ManyToManyField(
        Allergy,
        blank=True,
        verbose_name='Аллергии'
    )
    diet_type = models.ForeignKey(
        DietType,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Тип диеты'
    )
    budget_limit = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
        verbose_name='Ограничение по стоимости'
    )
    count_of_persons = models.IntegerField(
        default=1,
        verbose_name='Количество персон'
    )
    breakfast = models.BooleanField(
        default=True,
        verbose_name='Завтрак'
    )
    lunch = models.BooleanField(
        default=True,
        verbose_name='Обед'
    )
    dinner = models.BooleanField(
        default=True,
        verbose_name='Ужин'
    )
    dessert = models.BooleanField(
        default=False,
        verbose_name='Десерт'
    )
    subscription_end_date = models.DateField(
        null=True,
        blank=True,
        verbose_name='Дата окончания подписки'
    )
    avatar = models.ImageField(
        verbose_name='Аватар',
        upload_to='avatars/',
        null=True, blank=True
    )

    active_subscription = models.ForeignKey(
        SubscriptionOrder,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name='Активная подписка'
    )

    def __str__(self):
        return self.user.username


class Ingredient(models.Model):
    UNIT_CHOICES = [
        ('g', 'Граммы'),
        ('ml', 'Миллилитры'),
        ('pcs', 'Штуки'),
        ('tbsp', 'Столовые ложки'),
        ('tsp', 'Чайные ложки'),
    ]
    name = models.CharField(
        max_length=150,
        verbose_name='Название ингредиента'
    )
    allergens = models.ManyToManyField(
        Allergy,
        blank=True,
        verbose_name='Аллергены'
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2,
        verbose_name='Стоимость за единицу'
    )
    callories = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        verbose_name='Калорийность'
    )
    unit = models.CharField(
        max_length=10,
        choices=UNIT_CHOICES,
        default='g',
        verbose_name='Единица измерения'
    )

    def __str__(self):
        return f'{self.name} ({self.get_unit_display()})'


class Dish(models.Model):
    DISH_CATEGORY_CHOICES = [
        ('breakfast', 'Завтрак'),
        ('lunch', 'Обед'),
        ('dinner', 'Ужин'),
        ('dessert', 'Десерт')
    ]
    name = models.CharField(
        max_length=150,
        verbose_name='Название блюда'
    )
    description = models.TextField(
        verbose_name='Описание блюда'
    )
    recipe = models.TextField(
        verbose_name='Рецепт приготовления',
        blank=True,
        default=''
    )
    photo = models.ImageField(
        verbose_name='Фото блюда',
        blank=True,
        null=True,
        upload_to='dishes/'
    )
    diet_type = models.ForeignKey(
        DietType,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Тип меню'
    )
    ingredients = models.ManyToManyField(
        Ingredient,
        through='DishIngredient',
        verbose_name='Ингредиенты'
    )
    category = models.CharField(
        max_length=50,
        choices=DISH_CATEGORY_CHOICES,
        verbose_name='Категория блюда',
        default='lunch'
    )

    @property
    def total_price(self):
        return sum(
            di.quantity * di.ingredient.price
            for di in self.dishingredient_set.all()
        )

    @property
    def total_calories(self):
        return sum(
            di.quantity * di.ingredient.callories
            for di in self.dishingredient_set.all()
        )

    def __str__(self):
        return self.name


class DishIngredient(models.Model):
    dish = models.ForeignKey(
        Dish,
        on_delete=models.CASCADE
    )
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE
    )
    quantity = models.DecimalField(
        max_digits=10, decimal_places=2,
        verbose_name='Количество'
    )

    def __str__(self):
        return f'{self.ingredient} - {self.quantity}'

planner/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile, DietType


class LoginForm(forms.Form):
    username = forms.CharField(
        label="Логин",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )


class RegisterForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        label="Email",
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    username = forms.CharField(
        label="Логин",
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        help_text="Логин будет отображаться под аватаркой в личном кабинете"
    )
    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    diet_type = forms.ModelChoiceField(
        queryset=DietType.objects.all(),
        required=False,
        label="Тип диеты",
        widget=forms.Select(attrs={'class': 'form-select'})
    )


    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует")
        return email


class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField(
        label="Имя",
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    last_name = forms.CharField(
        label="Фамилия",
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    email = forms.EmailField(
        label="Email",
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    budget_limit = forms.DecimalField(
        label='Бюджет на один приём пищи (руб)',
        required=False,
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
        })
    )
    avatar = forms.ImageField(
        label='Аватар',
        required=False,
        widget=forms.FileInput(attrs={
            'class': 'form-control d-none',
            'id': 'avatar-upload'
        })
    )

    class Meta:
        model = UserProfile
        fields = ['budget_limit', 'avatar']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['first_name'].initial = user.first_name
        self.fields['last_name'].initial = user.last_name
        self.fields['email'].initial = user.email

    def save(self, commit=True):
        profile = super().save(commit=False)
        user = self.instance.user

        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
            profile.save()

        return profile

templates/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Foodplan 2021 - Меню на неделю FOODPLAN</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse1"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse1">
                    <ul class="navbar-nav w-100">
                        
                        <li class="nav-item align-items-center d-md-flex flex-grow-1 justify-content-end">
                            <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green">Войти</button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="card p-3 mb-5 foodplan__shadow">
                    <a href="#" class="link-secondary fw-light foodplan__backButton">
                        <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                            viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                    </a>
                    <h2 class="text-center"><strong>Авторизация</strong></h2>
                </div>
                <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
                    <form method="post" action="{% url 'auth' %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}">
                        <h1 class="mb-4 text-center"><strong>Вход</strong></h1>
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Логин</label>
                            <input type="text" class="form-control" id="id_username" name="username" required>
                        </div>
                        <div class="mb-3">
                            <div class="d-flex align-items-center justify-content-between">
                                <label for="id_password" class="form-label">Пароль</label>
                                <small><a href="#" class="link-dark foodplan_green">Забыли пароль?</a></small>
                            </div>
                            <input type="password" class="form-control" id="id_password" name="password" required>
                        </div>
                        <div class="row mb-3">
                            <div class="col-12 col-sm-6 mt-3">
                                <button type="submit" class="btn w-100 btn-outline-success shadow-none foodplan_green foodplan__border_green">Войти</button>
                            </div>
                            <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                                <small>Нет аккаунта? <a href="{% url 'registration' %}" class="link-dark foodplan_green">Зарегистрируйтесь</a></small>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="#">
                        <img src="{% static 'img/vk.png' %}" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6>
                <a href="#" class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/card.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{{ dish.name }} - рецепт</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <a href="{% url 'lk' %}" class="btn btn-outline-success me-2 shadow-none foodplan_green foodplan__border_green">Назад</a>
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 75px);">
        <section>
            <div class="container">
                <div class="row">
                    <!-- Изображение блюда -->
                    <div class="col-12 col-md-4 d-flex justify-content-center mb-4">
                        <div class="card foodplan__card_borderless">
                            <img src="{% if dish.photo %}{{ dish.photo.url }}{% else %}{% static 'img/default_dish.jpg' %}{% endif %}"
                                 alt="{{ dish.name }}"
                                 class="img-fluid rounded">
                        </div>
                    </div>

                    <!-- Основная информация -->
                    <div class="col-12 col-md-8">
                        <h2 class="mb-3">{{ dish.name }}</h2>

                        <div class="row align-items-stretch">
                            <!-- Рецепт -->
                            <div class="col-12 col-md-6 mb-3">
                                <div class="card h-100">
                                    <div class="card-body">
                                        <h5 class="card-title">Рецепт:</h5>
                                        <div class="card-text">
                                            {% for line in dish.recipe.splitlines %}
                                                <p>{{ line }}</p>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Ингредиенты и детали -->
                            <div class="col-12 col-md-6 mb-3">
                                <div class="card h-100">
                                    <div class="card-body d-flex flex-column">
                                        <h5 class="card-title">Ингредиенты:</h5>
                                        <ul class="list-group list-group-flush mb-3 flex-grow-1">
                                            {% for ingredient in ingredients %}
                                            <li class="list-group-item">
                                                <small>{{ ingredient.ingredient.name }} ({{ ingredient.quantity|floatformat }} {{ ingredient.unit }})</small>
                                            </li>
                                            {% endfor %}
                                        </ul>

                                        <div class="mt-auto">
                                            <small class="text-muted d-block">Общая калорийность: {{ dish.total_calories|floatformat }} ккал</small>
                                            <small class="text-muted d-block">Тип меню: {{ dish.diet_type.name }}</small>
                                            <small class="text-muted">Категория: {{ dish.get_category_display }}</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="#">
                        <img src="{% static 'img/vk.png' %}" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6>
                <a href="#" class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Foodplan 2021 - Меню на неделю FOODPLAN</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse1"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse1">
                    <ul class="navbar-nav w-100">
                        
                        <li class="nav-item align-items-center d-md-flex flex-grow-1 justify-content-end">
                            <button class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Войти</button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="card p-3 mb-5 foodplan__shadow">
                    <a href="#" class="link-secondary fw-light foodplan__backButton">
                        <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                            viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                    </a>
                    <h2 class="text-center"><strong>Авторизация</strong></h2>
                </div>
                <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
                    <form method="post" action="{% url 'registration' %}">
                        {% csrf_token %}
                        <h1 class="mb-4 text-center"><strong>Регистрация</strong></h1>
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Логин</label>
                            <input type="text" class="form-control" id="id_username" name="username" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_email" class="form-label">Email</label>
                            <input type="email" class="form-control" id="id_email" name="email" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_password1" class="form-label">Пароль</label>
                            <input type="password" class="form-control" id="id_password1" name="password1" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля</label>
                            <input type="password" class="form-control" id="id_password2" name="password2" required>
                        </div>
                        <div class="row mb-3">
                            <div class="col-12 col-sm-6 mt-3">
                                <button type="submit" class="btn shadow-none w-100 btn-outline-success foodplan_green foodplan__border_green">Регистрация</button>
                            </div>
                            <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                                <small>Уже есть аккаунт? <a href="{% url 'auth' %}" class="link-dark foodplan_green">Войти</a></small>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="#">
                        <img src="{% static 'img/vk.png' %}" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6><a href="#"
                    class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>